-- Generated seed data (mirrors the reference app's default plan). Run after schema.sql.
-- Safe to re-run a fresh load: it clears existing rows first.
truncate table public.topics, public.workstreams, public.activity, public.history restart identity cascade;
delete from public.settings;
insert into public.settings (id, start, version) values (1, '2026-06-18', 1);

insert into public.workstreams (id, name, color, sort_order) values ('sypfd8oo', 'Team & Culture', '#c2683a', 0);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('tn9879ew', 'sypfd8oo', 'Reestablish the weekly process meeting', '', '', 'not_started', 'high', 1, '2026-06-18', '2026-08-25', '[{"id":"06vpkti2","label":"Define agenda, owner & cadence","date":"2026-07-11","done":false},{"id":"daa2tvtt","label":"Hold first weekly meeting","date":"2026-08-02","done":false},{"id":"d1ls1d6d","label":"30-day cadence review","date":"2026-08-25","done":false}]'::jsonb, '[]'::jsonb, 0);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('hk2hg26d', 'sypfd8oo', 'Introduce a dedicated AI projects best-practices & status meeting', '', '', 'not_started', 'high', 1, '2026-06-18', '2026-08-25', '[{"id":"556y19c9","label":"Set format & invite list","date":"2026-07-11","done":false},{"id":"tvrii2i6","label":"Run first session","date":"2026-08-02","done":false},{"id":"0dww4l13","label":"Capture best-practices doc","date":"2026-08-25","done":false}]'::jsonb, '[]'::jsonb, 1);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('1xc7h6wy', 'sypfd8oo', 'Upgrade office environment and furniture', '', '', 'not_started', 'med', 2, '2026-09-18', '2026-11-25', '[{"id":"zj9wnl0d","label":"Assess needs & budget","date":"2026-10-11","done":false},{"id":"amhv9jiz","label":"Order furniture / fit-out","date":"2026-11-02","done":false},{"id":"urlkam29","label":"Complete installation","date":"2026-11-25","done":false}]'::jsonb, '[]'::jsonb, 2);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('mpuq55ym', 'sypfd8oo', 'Improve audio infrastructure for video conferences', '', '', 'not_started', 'high', 1, '2026-06-18', '2026-08-25', '[{"id":"q2uvua8r","label":"Audit current AV gaps","date":"2026-07-11","done":false},{"id":"ev7a3cyx","label":"Procure equipment","date":"2026-08-02","done":false},{"id":"lloj7sgi","label":"Install & test all rooms","date":"2026-08-25","done":false}]'::jsonb, '[]'::jsonb, 3);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('7r3328ee', 'sypfd8oo', 'Define and communicate clear roles for all team members', '', '', 'not_started', 'high', 1, '2026-06-18', '2026-08-25', '[{"id":"8byoo1d7","label":"Draft role descriptions","date":"2026-07-11","done":false},{"id":"g3zh5uxm","label":"Review with team","date":"2026-08-02","done":false},{"id":"u9dt3utl","label":"Publish & communicate","date":"2026-08-25","done":false}]'::jsonb, '[]'::jsonb, 4);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('tz65zv2o', 'sypfd8oo', 'CC to individually coach each team member', '', '', 'not_started', 'med', 2, '2026-09-18', '2026-11-25', '[{"id":"bmu0k6tr","label":"Schedule 1:1 cadence","date":"2026-10-11","done":false},{"id":"m4q1zks3","label":"First coaching round","date":"2026-11-02","done":false},{"id":"zg94z62w","label":"Quarterly progress review","date":"2026-11-25","done":false}]'::jsonb, '[]'::jsonb, 5);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('ipkw0rx4', 'sypfd8oo', 'Schedule an offsite & implement a recurring culture meeting', '', '', 'not_started', 'med', 2, '2026-09-18', '2026-11-25', '[{"id":"vnpji2mw","label":"Pick date & venue","date":"2026-10-11","done":false},{"id":"of8zqssn","label":"Run offsite","date":"2026-11-02","done":false},{"id":"1zy2f1ut","label":"Launch recurring culture meeting","date":"2026-11-25","done":false}]'::jsonb, '[]'::jsonb, 6);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('fxu6wg3l', 'sypfd8oo', 'Deliver two to three HBS case-study classes', '', '', 'not_started', 'med', 3, '2026-12-18', '2027-02-24', '[{"id":"7uppsrpt","label":"Select cases & facilitator","date":"2027-01-10","done":false},{"id":"nyav2iul","label":"Run first class","date":"2027-02-01","done":false},{"id":"d597bla3","label":"Complete class series","date":"2027-02-24","done":false}]'::jsonb, '[]'::jsonb, 7);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('cn166th8', 'sypfd8oo', 'Provide training in public speaking & meeting facilitation', '', '', 'not_started', 'low', 3, '2026-12-18', '2027-02-24', '[{"id":"zqxqpt3t","label":"Choose program / trainer","date":"2027-01-10","done":false},{"id":"9b6t467l","label":"First training session","date":"2027-02-01","done":false},{"id":"d3zm3giw","label":"Practice & feedback round","date":"2027-02-24","done":false}]'::jsonb, '[]'::jsonb, 8);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('94ek0ccp', 'sypfd8oo', 'Expand team social events (happy hours, lunches, sports)', '', '', 'not_started', 'low', 2, '2026-09-18', '2026-11-25', '[{"id":"r2caryd4","label":"Plan events calendar","date":"2026-10-11","done":false},{"id":"tqolpg43","label":"Host first events","date":"2026-11-02","done":false},{"id":"a4lkez3k","label":"Review engagement","date":"2026-11-25","done":false}]'::jsonb, '[]'::jsonb, 9);

insert into public.workstreams (id, name, color, sort_order) values ('ahoeppxd', 'Portfolio Management', '#2f6b5e', 1);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('sape95bo', 'ahoeppxd', 'Build an AI-powered online deal-flow panel', '', '', 'not_started', 'high', 2, '2026-09-18', '2026-11-25', '[{"id":"mwf60f8s","label":"Define requirements","date":"2026-10-11","done":false},{"id":"tmdzteh9","label":"Build MVP","date":"2026-11-02","done":false},{"id":"xxnm8ae8","label":"Roll out to team","date":"2026-11-25","done":false}]'::jsonb, '[]'::jsonb, 0);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('duu62due', 'ahoeppxd', 'Implement a local ERP system with AI integration', '', '', 'not_started', 'high', 3, '2026-12-18', '2027-02-24', '[{"id":"f7y0m1u5","label":"Select ERP & scope","date":"2027-01-10","done":false},{"id":"jmcfx6mv","label":"Configure & integrate AI","date":"2027-02-01","done":false},{"id":"evah5spj","label":"Go live","date":"2027-02-24","done":false}]'::jsonb, '[]'::jsonb, 1);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('y2eegmpd', 'ahoeppxd', 'Develop an AI-assisted exit calculator tool', '', '', 'not_started', 'med', 2, '2026-09-18', '2026-11-25', '[{"id":"mc4txy0m","label":"Define model logic","date":"2026-10-11","done":false},{"id":"9v6hbluj","label":"Build prototype","date":"2026-11-02","done":false},{"id":"adhbfvxx","label":"Validate with real deals","date":"2026-11-25","done":false}]'::jsonb, '[]'::jsonb, 2);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('88p9p400', 'ahoeppxd', 'Consolidate all controls & systems into a unified AI database (US & Brazil)', '', '', 'not_started', 'high', 3, '2026-12-18', '2027-02-24', '[{"id":"sw9bo34v","label":"Map existing systems","date":"2027-01-10","done":false},{"id":"szvbn55o","label":"Design unified schema","date":"2027-02-01","done":false},{"id":"1m1a8lje","label":"Migrate & validate data","date":"2027-02-24","done":false}]'::jsonb, '[]'::jsonb, 3);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('keqz7w3r', 'ahoeppxd', 'Integrate daily legal claims & portfolio movements into the AI ERP', '', '', 'not_started', 'med', 3, '2026-12-18', '2027-02-24', '[{"id":"5r0bt6m2","label":"Define data feeds","date":"2027-01-10","done":false},{"id":"vsup1un9","label":"Build integration","date":"2027-02-01","done":false},{"id":"djxdr0lj","label":"Confirm daily sync","date":"2027-02-24","done":false}]'::jsonb, '[]'::jsonb, 4);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('90inl1ro', 'ahoeppxd', 'Improve communication & visibility on settlements & exits', '', '', 'not_started', 'high', 1, '2026-06-18', '2026-08-25', '[{"id":"6w23cf3a","label":"Define reporting format","date":"2026-07-11","done":false},{"id":"gu823obb","label":"Set update cadence","date":"2026-08-02","done":false},{"id":"i4se3zqk","label":"First distribution","date":"2026-08-25","done":false}]'::jsonb, '[]'::jsonb, 5);

insert into public.workstreams (id, name, color, sort_order) values ('ja4xp489', 'Partners & SG Ecosystem', '#5b6aa8', 2);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('y8xwzjsh', 'ja4xp489', 'Implement formal governance for invested partners (Lass, VLS, Almina, Ticiano AI tool)', '', '', 'not_started', 'high', 2, '2026-09-18', '2026-11-25', '[{"id":"rdf2tnmz","label":"Define reports, meetings & controls","date":"2026-10-11","done":false},{"id":"4uva3cjt","label":"Agree cadence with partners","date":"2026-11-02","done":false},{"id":"4dadiflr","label":"First governance cycle","date":"2026-11-25","done":false}]'::jsonb, '[]'::jsonb, 0);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('lj34mhkj', 'ja4xp489', 'Standardize the Consignado proposal for partners', '', '', 'not_started', 'high', 1, '2026-06-18', '2026-08-25', '[{"id":"jpdv7cfs","label":"Draft standard proposal","date":"2026-07-11","done":false},{"id":"xmvpowro","label":"Internal review","date":"2026-08-02","done":false},{"id":"8hl0r6oq","label":"Approve & circulate","date":"2026-08-25","done":false}]'::jsonb, '[]'::jsonb, 1);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('v2fuq0nc', 'ja4xp489', 'Formalize the BLC proposal for partners', '', '', 'not_started', 'med', 1, '2026-06-18', '2026-08-25', '[{"id":"gf5noang","label":"Document framework","date":"2026-07-11","done":false},{"id":"a01zu4ah","label":"Legal / IC review","date":"2026-08-02","done":false},{"id":"t25as4c6","label":"Publish final proposal","date":"2026-08-25","done":false}]'::jsonb, '[]'::jsonb, 2);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('ozcqel5j', 'ja4xp489', 'Standardize the onboarding process for new partners', '', '', 'not_started', 'med', 2, '2026-09-18', '2026-11-25', '[{"id":"qk33oae7","label":"Map onboarding steps","date":"2026-10-11","done":false},{"id":"d1rnx6bh","label":"Build checklist & templates","date":"2026-11-02","done":false},{"id":"31ov4ofs","label":"Pilot with one partner","date":"2026-11-25","done":false}]'::jsonb, '[]'::jsonb, 3);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('5cx1foyx', 'ja4xp489', 'Designate a single point of contact for each partner', '', '', 'not_started', 'high', 1, '2026-06-18', '2026-08-25', '[{"id":"hjkzde26","label":"Map partners to owners","date":"2026-07-11","done":false},{"id":"knndhkbz","label":"Communicate to partners","date":"2026-08-02","done":false},{"id":"icv5w2qu","label":"Confirm coverage","date":"2026-08-25","done":false}]'::jsonb, '[]'::jsonb, 4);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('1pycmqph', 'ja4xp489', 'Implement a partner risk report (admin, regulatory, development)', '', '', 'not_started', 'med', 3, '2026-12-18', '2027-02-24', '[{"id":"3ubzyecw","label":"Define risk indicators","date":"2027-01-10","done":false},{"id":"jm4gpc6l","label":"Build report template","date":"2027-02-01","done":false},{"id":"v1srz8z2","label":"First reporting cycle","date":"2027-02-24","done":false}]'::jsonb, '[]'::jsonb, 5);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('dzbzllut', 'ja4xp489', 'Explore creation of a Consignado company modeled on Lass', '', '', 'not_started', 'low', 3, '2026-12-18', '2027-02-24', '[{"id":"0xtjsyfw","label":"Feasibility study","date":"2027-01-10","done":false},{"id":"4gpqjde2","label":"Business case & structure","date":"2027-02-01","done":false},{"id":"6cgd6ggq","label":"Go / no-go decision","date":"2027-02-24","done":false}]'::jsonb, '[]'::jsonb, 6);

insert into public.workstreams (id, name, color, sort_order) values ('l00o9jpl', 'Investing, Due Diligence & Risk', '#a8443a', 3);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('78kp0p7h', 'l00o9jpl', 'Develop a go/no-go checklist for new deals (pre-IC)', '', '', 'not_started', 'high', 1, '2026-06-18', '2026-08-25', '[{"id":"uzuzintv","label":"Draft checklist","date":"2026-07-11","done":false},{"id":"a8ac4xht","label":"Pilot on next deal","date":"2026-08-02","done":false},{"id":"v753s9tg","label":"Mandate before IC","date":"2026-08-25","done":false}]'::jsonb, '[]'::jsonb, 0);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('2qtjcwrb', 'l00o9jpl', 'Establish a pipeline meeting without CC', '', '', 'not_started', 'med', 1, '2026-06-18', '2026-08-25', '[{"id":"pbih97fw","label":"Set format & attendees","date":"2026-07-11","done":false},{"id":"uoqc392p","label":"Run first meeting","date":"2026-08-02","done":false},{"id":"9ptyld2t","label":"Cadence review","date":"2026-08-25","done":false}]'::jsonb, '[]'::jsonb, 1);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('ua978dnw', 'l00o9jpl', 'Merge the global BLC IC with the Consignado IC', '', '', 'not_started', 'med', 2, '2026-09-18', '2026-11-25', '[{"id":"25l5a5b2","label":"Align agendas & members","date":"2026-10-11","done":false},{"id":"7b3et5oo","label":"Define merged process","date":"2026-11-02","done":false},{"id":"0ovwtk7z","label":"First combined IC","date":"2026-11-25","done":false}]'::jsonb, '[]'::jsonb, 2);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('9hp18xbo', 'l00o9jpl', 'Receive regular reports on legal status of cases & theses', '', '', 'not_started', 'high', 1, '2026-06-18', '2026-08-25', '[{"id":"yusg6vkn","label":"Define report scope","date":"2026-07-11","done":false},{"id":"xn4631pr","label":"Set cadence","date":"2026-08-02","done":false},{"id":"9qu3asq6","label":"First report delivered","date":"2026-08-25","done":false}]'::jsonb, '[]'::jsonb, 3);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('2k3k836p', 'l00o9jpl', 'Sharpen focus & communication in local IC meetings', '', '', 'not_started', 'med', 1, '2026-06-18', '2026-08-25', '[{"id":"cltkmzea","label":"Define IC standards","date":"2026-07-11","done":false},{"id":"kagouikj","label":"Update agenda template","date":"2026-08-02","done":false},{"id":"ig39z8y7","label":"Review after 2 ICs","date":"2026-08-25","done":false}]'::jsonb, '[]'::jsonb, 4);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('sgjfprtf', 'l00o9jpl', 'Implement red/yellow/green flag reporting across risk layers (AI-monitored)', '', '', 'not_started', 'high', 3, '2026-12-18', '2027-02-24', '[{"id":"v9hhteil","label":"Define flag criteria","date":"2027-01-10","done":false},{"id":"ta7jsgei","label":"Build AI monitoring","date":"2027-02-01","done":false},{"id":"k823q3n9","label":"Roll out dashboard","date":"2027-02-24","done":false}]'::jsonb, '[]'::jsonb, 5);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('7x9e4z4g', 'l00o9jpl', 'Establish an in-office CCO function with AI support', '', '', 'not_started', 'high', 3, '2026-12-18', '2027-02-24', '[{"id":"ke4pnzd8","label":"Define CCO mandate","date":"2027-01-10","done":false},{"id":"4uec0mgi","label":"Assign & tool up","date":"2027-02-01","done":false},{"id":"s4udsrr9","label":"Operational review","date":"2027-02-24","done":false}]'::jsonb, '[]'::jsonb, 6);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('c6yxrln9', 'l00o9jpl', 'Create mandatory DD checklists for all asset classes', '', '', 'not_started', 'high', 2, '2026-09-18', '2026-11-25', '[{"id":"qgwt5nxn","label":"Draft per asset class","date":"2026-10-11","done":false},{"id":"bhucajkk","label":"Review with team","date":"2026-11-02","done":false},{"id":"jagi6s24","label":"Mandate across deals","date":"2026-11-25","done":false}]'::jsonb, '[]'::jsonb, 7);

insert into public.workstreams (id, name, color, sort_order) values ('yjogqkn3', 'Fundraising, PR & Investor Relations', '#b08527', 4);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('s2yjrr7b', 'yjogqkn3', 'Provide IR with regular portfolio updates', '', '', 'not_started', 'high', 1, '2026-06-18', '2026-08-25', '[{"id":"8757lam6","label":"Define update pack","date":"2026-07-11","done":false},{"id":"rm110bl8","label":"Set cadence","date":"2026-08-02","done":false},{"id":"4dm3rj81","label":"First update sent","date":"2026-08-25","done":false}]'::jsonb, '[]'::jsonb, 0);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('ofpv0p8e', 'yjogqkn3', 'Enhance investor communication with AI-assisted tools', '', '', 'not_started', 'med', 2, '2026-09-18', '2026-11-25', '[{"id":"3mwaoqfy","label":"Select tools","date":"2026-10-11","done":false},{"id":"kt16qrgj","label":"Build templates","date":"2026-11-02","done":false},{"id":"p5429umn","label":"Roll out to IR","date":"2026-11-25","done":false}]'::jsonb, '[]'::jsonb, 1);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('dx4xbitw', 'yjogqkn3', 'Increase events with local partners', '', '', 'not_started', 'med', 2, '2026-09-18', '2026-11-25', '[{"id":"f0hbxg3h","label":"Plan event calendar","date":"2026-10-11","done":false},{"id":"4995zibt","label":"Host first event","date":"2026-11-02","done":false},{"id":"ili1f07e","label":"Review pipeline impact","date":"2026-11-25","done":false}]'::jsonb, '[]'::jsonb, 2);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('3co8aytg', 'yjogqkn3', 'Strengthen local fundraising efforts', '', '', 'not_started', 'high', 2, '2026-09-18', '2026-11-25', '[{"id":"ozns4ll4","label":"Define target investors","date":"2026-10-11","done":false},{"id":"tbb8zdnd","label":"Outreach plan","date":"2026-11-02","done":false},{"id":"c5z0fudd","label":"First commitments","date":"2026-11-25","done":false}]'::jsonb, '[]'::jsonb, 3);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('lxkgsxfb', 'yjogqkn3', 'Develop a local fundraising strategy for US products (e.g., XP)', '', '', 'not_started', 'med', 3, '2026-12-18', '2027-02-24', '[{"id":"5zb5t4i7","label":"Market & product analysis","date":"2027-01-10","done":false},{"id":"ik9krnla","label":"Draft strategy","date":"2027-02-01","done":false},{"id":"a416ars4","label":"Approve & launch","date":"2027-02-24","done":false}]'::jsonb, '[]'::jsonb, 4);

