-- Generated seed data (mirrors the reference app's default plan). Run after schema.sql.
-- Safe to re-run a fresh load: it clears existing rows first.
truncate table public.topics, public.workstreams, public.activity, public.history restart identity cascade;
delete from public.settings;
insert into public.settings (id, start, version) values (1, '2026-06-18', 1);

insert into public.workstreams (id, name, color, sort_order) values ('d4r63r44', 'Team & Culture', '#c2683a', 0);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('1epulhpz', 'd4r63r44', 'Reestablish the weekly process meeting', '', '', 'not_started', 'high', 1, null, '2026-08-25', '[{"id":"n200hsvq","label":"Define agenda, owner & cadence","date":"2026-07-11","done":false},{"id":"hddrn5np","label":"Hold first weekly meeting","date":"2026-08-02","done":false},{"id":"8y0wp06y","label":"30-day cadence review","date":"2026-08-25","done":false}]'::jsonb, '[]'::jsonb, 0);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('pjeu9vcu', 'd4r63r44', 'Introduce a dedicated AI projects best-practices & status meeting', '', '', 'not_started', 'high', 1, null, '2026-08-25', '[{"id":"0x1pqvma","label":"Set format & invite list","date":"2026-07-11","done":false},{"id":"o1jsbtsg","label":"Run first session","date":"2026-08-02","done":false},{"id":"nnb3l22r","label":"Capture best-practices doc","date":"2026-08-25","done":false}]'::jsonb, '[]'::jsonb, 1);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('ipwa2j77', 'd4r63r44', 'Upgrade office environment and furniture', '', '', 'not_started', 'med', 2, null, '2026-11-25', '[{"id":"4x8apmj5","label":"Assess needs & budget","date":"2026-10-11","done":false},{"id":"p22m7p9k","label":"Order furniture / fit-out","date":"2026-11-02","done":false},{"id":"4sxlirne","label":"Complete installation","date":"2026-11-25","done":false}]'::jsonb, '[]'::jsonb, 2);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('59f5exrb', 'd4r63r44', 'Improve audio infrastructure for video conferences', '', '', 'not_started', 'high', 1, null, '2026-08-25', '[{"id":"y1h9dui5","label":"Audit current AV gaps","date":"2026-07-11","done":false},{"id":"tt1o8bvo","label":"Procure equipment","date":"2026-08-02","done":false},{"id":"d2rz1nht","label":"Install & test all rooms","date":"2026-08-25","done":false}]'::jsonb, '[]'::jsonb, 3);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('y9hy6gex', 'd4r63r44', 'Define and communicate clear roles for all team members', '', '', 'not_started', 'high', 1, null, '2026-08-25', '[{"id":"y9hsxwt9","label":"Draft role descriptions","date":"2026-07-11","done":false},{"id":"83vqu7bs","label":"Review with team","date":"2026-08-02","done":false},{"id":"gxro1zu7","label":"Publish & communicate","date":"2026-08-25","done":false}]'::jsonb, '[]'::jsonb, 4);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('1zr4d5o0', 'd4r63r44', 'CC to individually coach each team member', '', '', 'not_started', 'med', 2, null, '2026-11-25', '[{"id":"laegoyzh","label":"Schedule 1:1 cadence","date":"2026-10-11","done":false},{"id":"ibxofcxz","label":"First coaching round","date":"2026-11-02","done":false},{"id":"w2p0fse6","label":"Quarterly progress review","date":"2026-11-25","done":false}]'::jsonb, '[]'::jsonb, 5);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('7a2e6poq', 'd4r63r44', 'Schedule an offsite & implement a recurring culture meeting', '', '', 'not_started', 'med', 2, null, '2026-11-25', '[{"id":"fw1ghlfc","label":"Pick date & venue","date":"2026-10-11","done":false},{"id":"hjhu2req","label":"Run offsite","date":"2026-11-02","done":false},{"id":"upx2pxdj","label":"Launch recurring culture meeting","date":"2026-11-25","done":false}]'::jsonb, '[]'::jsonb, 6);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('k2jzzfl8', 'd4r63r44', 'Deliver two to three HBS case-study classes', '', '', 'not_started', 'med', 3, null, '2027-02-24', '[{"id":"4q470qmr","label":"Select cases & facilitator","date":"2027-01-10","done":false},{"id":"jymm5wk7","label":"Run first class","date":"2027-02-01","done":false},{"id":"0vg1wcfm","label":"Complete class series","date":"2027-02-24","done":false}]'::jsonb, '[]'::jsonb, 7);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('gvm8h2lq', 'd4r63r44', 'Provide training in public speaking & meeting facilitation', '', '', 'not_started', 'low', 3, null, '2027-02-24', '[{"id":"q068o2zh","label":"Choose program / trainer","date":"2027-01-10","done":false},{"id":"6juv6fpb","label":"First training session","date":"2027-02-01","done":false},{"id":"tvlzpaj7","label":"Practice & feedback round","date":"2027-02-24","done":false}]'::jsonb, '[]'::jsonb, 8);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('2kzvk4hf', 'd4r63r44', 'Expand team social events (happy hours, lunches, sports)', '', '', 'not_started', 'low', 2, null, '2026-11-25', '[{"id":"2l05hu6s","label":"Plan events calendar","date":"2026-10-11","done":false},{"id":"ok00blar","label":"Host first events","date":"2026-11-02","done":false},{"id":"mnbnlsbi","label":"Review engagement","date":"2026-11-25","done":false}]'::jsonb, '[]'::jsonb, 9);

insert into public.workstreams (id, name, color, sort_order) values ('zujdh67n', 'Portfolio Management', '#2f6b5e', 1);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('9dlgavwx', 'zujdh67n', 'Build an AI-powered online deal-flow panel', '', '', 'not_started', 'high', 2, null, '2026-11-25', '[{"id":"g77mme56","label":"Define requirements","date":"2026-10-11","done":false},{"id":"02cj55aw","label":"Build MVP","date":"2026-11-02","done":false},{"id":"eda4qp89","label":"Roll out to team","date":"2026-11-25","done":false}]'::jsonb, '[]'::jsonb, 0);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('6u7ja7ta', 'zujdh67n', 'Implement a local ERP system with AI integration', '', '', 'not_started', 'high', 3, null, '2027-02-24', '[{"id":"vdenol9d","label":"Select ERP & scope","date":"2027-01-10","done":false},{"id":"o26vdmif","label":"Configure & integrate AI","date":"2027-02-01","done":false},{"id":"fcpuqrjn","label":"Go live","date":"2027-02-24","done":false}]'::jsonb, '[]'::jsonb, 1);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('6kdci0wj', 'zujdh67n', 'Develop an AI-assisted exit calculator tool', '', '', 'not_started', 'med', 2, null, '2026-11-25', '[{"id":"92vs8iug","label":"Define model logic","date":"2026-10-11","done":false},{"id":"24fx8jgz","label":"Build prototype","date":"2026-11-02","done":false},{"id":"u2r9m8sp","label":"Validate with real deals","date":"2026-11-25","done":false}]'::jsonb, '[]'::jsonb, 2);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('h8ywwflz', 'zujdh67n', 'Consolidate all controls & systems into a unified AI database (US & Brazil)', '', '', 'not_started', 'high', 3, null, '2027-02-24', '[{"id":"b0xpjyz0","label":"Map existing systems","date":"2027-01-10","done":false},{"id":"tvn7ub2a","label":"Design unified schema","date":"2027-02-01","done":false},{"id":"mits1ysv","label":"Migrate & validate data","date":"2027-02-24","done":false}]'::jsonb, '[]'::jsonb, 3);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('yxlh0l5c', 'zujdh67n', 'Integrate daily legal claims & portfolio movements into the AI ERP', '', '', 'not_started', 'med', 3, null, '2027-02-24', '[{"id":"s9l7nk07","label":"Define data feeds","date":"2027-01-10","done":false},{"id":"e02a5zqc","label":"Build integration","date":"2027-02-01","done":false},{"id":"clm7us1q","label":"Confirm daily sync","date":"2027-02-24","done":false}]'::jsonb, '[]'::jsonb, 4);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('yuoc932o', 'zujdh67n', 'Improve communication & visibility on settlements & exits', '', '', 'not_started', 'high', 1, null, '2026-08-25', '[{"id":"mkbq78a8","label":"Define reporting format","date":"2026-07-11","done":false},{"id":"g5fr4xwn","label":"Set update cadence","date":"2026-08-02","done":false},{"id":"an4ghqi5","label":"First distribution","date":"2026-08-25","done":false}]'::jsonb, '[]'::jsonb, 5);

insert into public.workstreams (id, name, color, sort_order) values ('bn6ab0hv', 'Partners & SG Ecosystem', '#5b6aa8', 2);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('5qwi8u38', 'bn6ab0hv', 'Implement formal governance for invested partners (Lass, VLS, Almina, Ticiano AI tool)', '', '', 'not_started', 'high', 2, null, '2026-11-25', '[{"id":"wgpx7coz","label":"Define reports, meetings & controls","date":"2026-10-11","done":false},{"id":"rzot22r5","label":"Agree cadence with partners","date":"2026-11-02","done":false},{"id":"w24y6qny","label":"First governance cycle","date":"2026-11-25","done":false}]'::jsonb, '[]'::jsonb, 0);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('59dzbciy', 'bn6ab0hv', 'Standardize the Consignado proposal for partners', '', '', 'not_started', 'high', 1, null, '2026-08-25', '[{"id":"56rosjsc","label":"Draft standard proposal","date":"2026-07-11","done":false},{"id":"pnm5mc4l","label":"Internal review","date":"2026-08-02","done":false},{"id":"yec7zugu","label":"Approve & circulate","date":"2026-08-25","done":false}]'::jsonb, '[]'::jsonb, 1);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('jobk0zgl', 'bn6ab0hv', 'Formalize the BLC proposal for partners', '', '', 'not_started', 'med', 1, null, '2026-08-25', '[{"id":"q4o8afsa","label":"Document framework","date":"2026-07-11","done":false},{"id":"83s6fp45","label":"Legal / IC review","date":"2026-08-02","done":false},{"id":"yuxhuzow","label":"Publish final proposal","date":"2026-08-25","done":false}]'::jsonb, '[]'::jsonb, 2);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('fnpmu80h', 'bn6ab0hv', 'Standardize the onboarding process for new partners', '', '', 'not_started', 'med', 2, null, '2026-11-25', '[{"id":"a8eqcsp2","label":"Map onboarding steps","date":"2026-10-11","done":false},{"id":"ho0z1prg","label":"Build checklist & templates","date":"2026-11-02","done":false},{"id":"5px37ylz","label":"Pilot with one partner","date":"2026-11-25","done":false}]'::jsonb, '[]'::jsonb, 3);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('exvlarzz', 'bn6ab0hv', 'Designate a single point of contact for each partner', '', '', 'not_started', 'high', 1, null, '2026-08-25', '[{"id":"iimadauj","label":"Map partners to owners","date":"2026-07-11","done":false},{"id":"bgp6ehiv","label":"Communicate to partners","date":"2026-08-02","done":false},{"id":"f75g4vb9","label":"Confirm coverage","date":"2026-08-25","done":false}]'::jsonb, '[]'::jsonb, 4);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('9v4ymy3h', 'bn6ab0hv', 'Implement a partner risk report (admin, regulatory, development)', '', '', 'not_started', 'med', 3, null, '2027-02-24', '[{"id":"zhi3yhrn","label":"Define risk indicators","date":"2027-01-10","done":false},{"id":"nby2tb2f","label":"Build report template","date":"2027-02-01","done":false},{"id":"hwk704g1","label":"First reporting cycle","date":"2027-02-24","done":false}]'::jsonb, '[]'::jsonb, 5);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('mxtc18ih', 'bn6ab0hv', 'Explore creation of a Consignado company modeled on Lass', '', '', 'not_started', 'low', 3, null, '2027-02-24', '[{"id":"qo5xlqr6","label":"Feasibility study","date":"2027-01-10","done":false},{"id":"267hid7c","label":"Business case & structure","date":"2027-02-01","done":false},{"id":"87hi86nb","label":"Go / no-go decision","date":"2027-02-24","done":false}]'::jsonb, '[]'::jsonb, 6);

insert into public.workstreams (id, name, color, sort_order) values ('2q0grxyq', 'Investing, Due Diligence & Risk', '#a8443a', 3);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('ptruw16j', '2q0grxyq', 'Develop a go/no-go checklist for new deals (pre-IC)', '', '', 'not_started', 'high', 1, null, '2026-08-25', '[{"id":"km5e8yfj","label":"Draft checklist","date":"2026-07-11","done":false},{"id":"7vvchjau","label":"Pilot on next deal","date":"2026-08-02","done":false},{"id":"mdoapwyi","label":"Mandate before IC","date":"2026-08-25","done":false}]'::jsonb, '[]'::jsonb, 0);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('tlmfgjoc', '2q0grxyq', 'Establish a pipeline meeting without CC', '', '', 'not_started', 'med', 1, null, '2026-08-25', '[{"id":"8gxbc19u","label":"Set format & attendees","date":"2026-07-11","done":false},{"id":"zbko6mr2","label":"Run first meeting","date":"2026-08-02","done":false},{"id":"4xywpz85","label":"Cadence review","date":"2026-08-25","done":false}]'::jsonb, '[]'::jsonb, 1);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('rbeonyct', '2q0grxyq', 'Merge the global BLC IC with the Consignado IC', '', '', 'not_started', 'med', 2, null, '2026-11-25', '[{"id":"5nwy8kzn","label":"Align agendas & members","date":"2026-10-11","done":false},{"id":"cjqkn906","label":"Define merged process","date":"2026-11-02","done":false},{"id":"en6t0z1p","label":"First combined IC","date":"2026-11-25","done":false}]'::jsonb, '[]'::jsonb, 2);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('zyf5gzzl', '2q0grxyq', 'Receive regular reports on legal status of cases & theses', '', '', 'not_started', 'high', 1, null, '2026-08-25', '[{"id":"qldl8sj4","label":"Define report scope","date":"2026-07-11","done":false},{"id":"4lyguxrv","label":"Set cadence","date":"2026-08-02","done":false},{"id":"833oua5u","label":"First report delivered","date":"2026-08-25","done":false}]'::jsonb, '[]'::jsonb, 3);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('eistuka9', '2q0grxyq', 'Sharpen focus & communication in local IC meetings', '', '', 'not_started', 'med', 1, null, '2026-08-25', '[{"id":"somi10ef","label":"Define IC standards","date":"2026-07-11","done":false},{"id":"o6h8q89m","label":"Update agenda template","date":"2026-08-02","done":false},{"id":"jlfhbwxo","label":"Review after 2 ICs","date":"2026-08-25","done":false}]'::jsonb, '[]'::jsonb, 4);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('913khyif', '2q0grxyq', 'Implement red/yellow/green flag reporting across risk layers (AI-monitored)', '', '', 'not_started', 'high', 3, null, '2027-02-24', '[{"id":"z0q21vpz","label":"Define flag criteria","date":"2027-01-10","done":false},{"id":"s0efof15","label":"Build AI monitoring","date":"2027-02-01","done":false},{"id":"xw6zr5tv","label":"Roll out dashboard","date":"2027-02-24","done":false}]'::jsonb, '[]'::jsonb, 5);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('3ckdh60m', '2q0grxyq', 'Establish an in-office CCO function with AI support', '', '', 'not_started', 'high', 3, null, '2027-02-24', '[{"id":"8kh0m3x7","label":"Define CCO mandate","date":"2027-01-10","done":false},{"id":"4z6fdv5s","label":"Assign & tool up","date":"2027-02-01","done":false},{"id":"06k9f0jt","label":"Operational review","date":"2027-02-24","done":false}]'::jsonb, '[]'::jsonb, 6);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('p415ryxl', '2q0grxyq', 'Create mandatory DD checklists for all asset classes', '', '', 'not_started', 'high', 2, null, '2026-11-25', '[{"id":"sexwmvjc","label":"Draft per asset class","date":"2026-10-11","done":false},{"id":"ogfe17eu","label":"Review with team","date":"2026-11-02","done":false},{"id":"qi806ob5","label":"Mandate across deals","date":"2026-11-25","done":false}]'::jsonb, '[]'::jsonb, 7);

insert into public.workstreams (id, name, color, sort_order) values ('zmba058o', 'Fundraising, PR & Investor Relations', '#b08527', 4);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('77owwf7i', 'zmba058o', 'Provide IR with regular portfolio updates', '', '', 'not_started', 'high', 1, null, '2026-08-25', '[{"id":"3zguon2w","label":"Define update pack","date":"2026-07-11","done":false},{"id":"fvhtvuvn","label":"Set cadence","date":"2026-08-02","done":false},{"id":"rcariio6","label":"First update sent","date":"2026-08-25","done":false}]'::jsonb, '[]'::jsonb, 0);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('vy2j087r', 'zmba058o', 'Enhance investor communication with AI-assisted tools', '', '', 'not_started', 'med', 2, null, '2026-11-25', '[{"id":"90u75x75","label":"Select tools","date":"2026-10-11","done":false},{"id":"netijg4j","label":"Build templates","date":"2026-11-02","done":false},{"id":"tihbi2uc","label":"Roll out to IR","date":"2026-11-25","done":false}]'::jsonb, '[]'::jsonb, 1);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('ctxuqwqn', 'zmba058o', 'Increase events with local partners', '', '', 'not_started', 'med', 2, null, '2026-11-25', '[{"id":"oznq5r2b","label":"Plan event calendar","date":"2026-10-11","done":false},{"id":"x6olnb3a","label":"Host first event","date":"2026-11-02","done":false},{"id":"540phgw3","label":"Review pipeline impact","date":"2026-11-25","done":false}]'::jsonb, '[]'::jsonb, 2);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('auygqv2q', 'zmba058o', 'Strengthen local fundraising efforts', '', '', 'not_started', 'high', 2, null, '2026-11-25', '[{"id":"loxkw29x","label":"Define target investors","date":"2026-10-11","done":false},{"id":"xmthxb56","label":"Outreach plan","date":"2026-11-02","done":false},{"id":"zuyrjrzq","label":"First commitments","date":"2026-11-25","done":false}]'::jsonb, '[]'::jsonb, 3);
insert into public.topics (id, workstream_id, title, owner, owner2, status, priority, phase, start, due, checkpoints, notes, sort_order) values ('e9y5pin1', 'zmba058o', 'Develop a local fundraising strategy for US products (e.g., XP)', '', '', 'not_started', 'med', 3, null, '2027-02-24', '[{"id":"h3qh73gf","label":"Market & product analysis","date":"2027-01-10","done":false},{"id":"71f3u37p","label":"Draft strategy","date":"2027-02-01","done":false},{"id":"2ero3pbb","label":"Approve & launch","date":"2027-02-24","done":false}]'::jsonb, '[]'::jsonb, 4);

